apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
      - name: backend
        image: hack4laengage/engage_backend_service
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "250m"
            memory: "1024Mi"
        ports:
        - containerPort: 8000
          protocol: TCP
          name: http
        env:
        - name: ENGAGE_DEBUG
          valueFrom:
            secretKeyRef:
              name: engage-secrets
              key: ENGAGE_DEBUG
        - name: ENGAGE_TEST
          valueFrom:
            secretKeyRef:
              name: engage-secrets
              key: ENGAGE_TEST
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_DB
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DJANGO_SECRET_KEY
        - name: ENGAGE_SWAGGER_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: ENGAGE_SWAGGER_URL
        - name: MAILCHIMP_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: MAILCHIMP_KEY
        - name: MAILCHIMP_REGION
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: MAILCHIMP_REGION
        - name: MAILCHIMP_USER
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: MAILCHIMP_USER
        - name: RECAPTCHAKEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: RECAPTCHAKEY
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: MJ_API_KEY 
          valueFrom:
            secretKeyRef:
              name: mj-secrets
              key: MJ_API_KEY
        - name: MJ_API_SECRET
          valueFrom:
            secretKeyRef:
              name: mj-secrets
              key: MJ_API_SECRET
