apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: backend-crt
  namespace: default
spec:
  secretName: backend-crt
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
  - backend.engage.town
